# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'test_anilibria_api.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests


class Ui_MainWindow(object):
    def __init__(self):
        self.start_button_2 = None
        self.menu0 = None
        self.statusbar = None
        self.response = None
        self.menubar = None
        self.label = None
        self.request_input = None
        self.request_type = None
        self.centralwidget = None
        self.start_button = None

    def clicked_start(self):
        response = requests.get(url='https://api.anilibria.tv/v3/title', params={'code': 'kizumonogatari-iii-reiketsu-hen'})
        print(os.environ['AUTH_MAIL'])

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(550, 480, 231, 71))
        self.start_button.setObjectName("start_button")
        self.request_type = QtWidgets.QListWidget(self.centralwidget)
        self.request_type.setGeometry(QtCore.QRect(20, 20, 331, 541))
        self.request_type.setObjectName("request_type")
        self.request_input = QtWidgets.QLineEdit(self.centralwidget)
        self.request_input.setGeometry(QtCore.QRect(370, 50, 391, 21))
        self.request_input.setObjectName("request_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 30, 55, 16))
        self.label.setObjectName("label")
        self.response = QtWidgets.QListView(self.centralwidget)
        self.response.setGeometry(QtCore.QRect(370, 80, 401, 391))
        self.response.setObjectName("response")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 26))
        self.menubar.setObjectName("menubar")
        self.menu0 = QtWidgets.QMenu(self.menubar)
        self.menu0.setObjectName("menu0")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.start_button_2 = QtWidgets.QAction(MainWindow)
        self.start_button_2.setObjectName("start_button_2")
        self.menu0.addAction(self.start_button_2)
        self.menubar.addAction(self.menu0.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.request_type.addItem('get_title()')

        self.start_button.clicked.connect(self.clicked_start)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TEST_API"))
        self.start_button.setText(_translate("MainWindow", "start"))
        self.label.setText(_translate("MainWindow", "request"))
        self.menu0.setTitle(_translate("MainWindow", "0"))
        self.start_button_2.setText(_translate("MainWindow", "requestApi"))
        self.start_button_2.setToolTip(_translate("MainWindow", "requests to api"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
